spring:
  application:
    name: code-analyzer
  shell:
    interactive:
      enabled: true

logging:
  level:
    org.springframework.shell: DEBUG

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: ${AI_MODEL_NAME:qwen2.5-coder}
      temperature: 0.2
      timeout: 5m