octopus:
  version: "@project.version@"

spring:
  application:
    name: blue-ring-octopus-cli
  shell:
    interactive:
      enabled: false
  main:
    banner-mode: off # Spring Boot yazısını kaldırır

logging:
  file:
    name: logs/octopus.log
  threshold:
    console: "OFF"
  level:
    root: WARN
    org.jline: ERROR

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434                # Localde JDK25 varsa ve EXE dosyası ile aynı klasördeyse
      # base-url: http://host.docker.internal:11434   # Docker ile ayağa kaldırıldıysa
      model-name: ${AI_MODEL_NAME:qwen2.5-coder}
      temperature: 0.2
      timeout: 5m